### ISSUE TITLE
Readme file: Links to Documentation are broken

### ISSUE THREAD

**Issue by talfco** [paritytech/oo7#20]
The Documentation links to the github pages are broken.

**Comment by daviddao** [comment]
This probably helps a little but is still v0.6.0 and not v0.7.x

**Comment by ltfschoen** [comment]
I think the relevant docs are:
* https://wiki.parity.io/oo7-Parity-Reference
* https://wiki.parity.io/oo7-Parity-Examples

**Comment by ltfschoen** [comment]
https://tomusdrw.github.io/oo7/

**Comment by ltfschoen** [comment]
@tomusdrw hey I noticed that this issue is still open

it's a legacy PR that I think was on hold for a while until CLAs were integrated into the repo

it was working last month, but now the link to https://tomusdrw.github.io/oo7/ is broken

in addition to broken links in the oo7 readme https://github.com/paritytech/oo7#documentation, we now also have broken links in the Substrate Collectables Workshop where we are also referring to it in:
* https://shawntabrizi.github.io/substrate-collectables-workshop/#/4/introduction?id=what-to-expect
* https://shawntabrizi.github.io/substrate-collectables-workshop/#/0/interacting-with-your-node

do we want to restore https://tomusdrw.github.io/oo7/ or should we host the docs elsewhere?

**Comment by tomusdrw** [comment]
@ltfschoen  Let's fix the documentation here: https://paritytech.github.io/oo7/ and make it part of the build to push the docs.

I'm going to revive my personal `oo7` repo and just make a redirection.

**Comment by shawntabrizi** [comment]
@tomusdrw @ltfschoen Looks like this is now resolved after adding a Jekyll theme. Should we close?

**Comment by tomusdrw** [comment]
@shawntabrizi we still should push new version to `gh-pages` on every build, but we can open a separate issue for that.
